name = "BasisCommon"
uuid = "a97b1a4c-373c-40ef-8b4f-af7d11dc25a7"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
CassetteOverlay = "d78b62d4-37fa-4a6f-acd8-2f19986eb9ee"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
LocalRegistry = "89398ba2-070a-4b16-a995-9893c55d93cf"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Spec = "b8ccf107-3a88-5e0f-823b-b838c6a0f327"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
LocalRegistry = "0.5.7"
